"""initial schema

Revision ID: 327aeb2a65ec
Revises:
Create Date: 2026-07-08 14:12:23.158227
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "327aeb2a65ec"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("task_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("vector_bytes", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("dimensions > 0", name="ck_embedding_dimensions_positive"),
        sa.CheckConstraint("hit_count >= 0", name="ck_embedding_cache_hits"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_hash",
            "model_name",
            "dimensions",
            "task_type",
            name="uq_embedding_cache_identity",
        ),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prompt_name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template_checksum", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("variables_schema", sa.JSON(), nullable=False),
        sa.Column(
            "response_schema_name", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("active", "retired", name="promptstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("version >= 1", name="ck_prompt_version_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prompt_name", "version", name="uq_prompt_name_version"),
    )
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.create_index("ix_prompt_name_status", ["prompt_name", "status"], unique=False)

    op.create_table(
        "generation_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "roadmap",
                "skill",
                "task",
                "subtask",
                "project",
                "resource",
                name="entitytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "request_fingerprint", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("completeness_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("personalization_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("logical_ordering_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("skill_progression_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("duplicate_avoidance_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("hour_consistency_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("json_correctness_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("weighted_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("hard_failures", sa.JSON(), nullable=False),
        sa.Column("feedback", sa.JSON(), nullable=False),
        sa.Column("evaluator_prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("evaluator_model", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("attempt_number >= 1", name="ck_evaluation_attempt_positive"),
        sa.CheckConstraint(
            "weighted_score >= 0 AND weighted_score <= 1", name="ck_evaluation_weighted_score"
        ),
        sa.ForeignKeyConstraint(
            ["evaluator_prompt_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generation_evaluations", schema=None) as batch_op:
        batch_op.create_index("ix_evaluation_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_evaluation_fingerprint", ["request_fingerprint"], unique=False)

    op.create_table(
        "response_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=True),
        sa.Column(
            "namespace",
            sa.Enum(
                "roadmap",
                "project",
                "query_expansion",
                "follow_up",
                name="cachenamespace",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("cache_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("request_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("schema_version", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("quality_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("hit_count >= 0", name="ck_response_cache_hits"),
        sa.ForeignKeyConstraint(["prompt_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "cache_key", name="uq_response_cache_key"),
    )
    with op.batch_alter_table("response_cache", schema=None) as batch_op:
        batch_op.create_index("ix_response_cache_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_response_cache_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "roadmaps",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("goal_title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("goal_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "experience_level",
            sa.Enum(
                "beginner", "intermediate", "advanced", name="experiencelevel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "learning_style",
            sa.Enum(
                "visual", "reading", "hands_on", "mixed", name="learningstyle", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("weekly_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("estimated_hours", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", name="roadmapstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("indexed_content_version", sa.Integer(), nullable=True),
        sa.Column(
            "index_status",
            sa.Enum(
                "pending", "indexing", "ready", "failed", name="indexstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("indexed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "request_fingerprint", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("generation_prompt_version_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("content_version >= 1", name="ck_roadmap_content_version"),
        sa.CheckConstraint("estimated_hours > 0", name="ck_roadmap_hours_positive"),
        sa.CheckConstraint(
            "indexed_content_version IS NULL OR indexed_content_version <= content_version",
            name="ck_roadmap_indexed_version",
        ),
        sa.CheckConstraint("weekly_hours > 0", name="ck_roadmap_weekly_hours_positive"),
        sa.ForeignKeyConstraint(
            ["generation_prompt_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roadmaps", schema=None) as batch_op:
        batch_op.create_index(
            "ix_roadmap_index_recovery", ["index_status", "updated_at"], unique=False
        )
        batch_op.create_index(
            "ix_roadmap_learner_created", ["learner_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_roadmap_learner_fingerprint", ["learner_id", "request_fingerprint"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_roadmaps_learner_id"), ["learner_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("roadmap_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="conversationstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("next_sequence", sa.Integer(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("next_sequence >= 1", name="ck_conversation_next_sequence"),
        sa.ForeignKeyConstraint(["roadmap_id"], ["roadmaps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "learner_id", name="uq_conversation_id_learner"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversation_learner_recent", ["learner_id", "last_message_at"], unique=False
        )
        batch_op.create_index(
            "ix_conversation_roadmap_recent", ["roadmap_id", "last_message_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_learner_id"), ["learner_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("roadmap_id", sa.Uuid(), nullable=True),
        sa.Column("goal_title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=220), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("beginner", "intermediate", "advanced", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.Column("estimated_hours", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("requirements", sa.JSON(), nullable=False),
        sa.Column("deliverables", sa.JSON(), nullable=False),
        sa.Column("acceptance_criteria", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "proposed",
                "active",
                "completed",
                "archived",
                name="projectstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "request_fingerprint", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False
        ),
        sa.Column("generation_prompt_version_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("estimated_hours > 0", name="ck_project_hours_positive"),
        sa.ForeignKeyConstraint(
            ["generation_prompt_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["roadmap_id"], ["roadmaps.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_learner_created", ["learner_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_project_learner_fingerprint", ["learner_id", "request_fingerprint"], unique=False
        )
        batch_op.create_index(
            "ix_project_roadmap_created", ["roadmap_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_projects_learner_id"), ["learner_id"], unique=False)

    op.create_table(
        "skills",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("roadmap_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "target_proficiency", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False
        ),
        sa.Column("estimated_hours", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.CheckConstraint("estimated_hours > 0", name="ck_skill_hours_positive"),
        sa.CheckConstraint("order_index >= 0", name="ck_skill_order_nonnegative"),
        sa.ForeignKeyConstraint(["roadmap_id"], ["roadmaps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("roadmap_id", "order_index", name="uq_skill_roadmap_order"),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index("ix_skill_roadmap_title", ["roadmap_id", "title"], unique=False)

    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", "system", name="messagerole", native_enum=False),
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "processing_status",
            sa.Enum("pending", "processed", "failed", name="processingstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("source_citations", sa.JSON(), nullable=True),
        sa.Column("retrieval_summary", sa.JSON(), nullable=True),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "completion_tokens IS NULL OR completion_tokens >= 0",
            name="ck_message_completion_tokens",
        ),
        sa.CheckConstraint(
            "prompt_tokens IS NULL OR prompt_tokens >= 0", name="ck_message_prompt_tokens"
        ),
        sa.CheckConstraint("sequence_number >= 1", name="ck_message_sequence_positive"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prompt_version_id"], ["prompt_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "sequence_number", name="uq_message_sequence"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_message_conversation_created", ["conversation_id", "created_at"], unique=False
        )

    op.create_table(
        "project_skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("roadmap_skill_id", sa.Uuid(), nullable=True),
        sa.Column("skill_name", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.CheckConstraint("order_index >= 0", name="ck_project_skill_order_nonnegative"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["roadmap_skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "order_index", name="uq_project_skill_order"),
        sa.UniqueConstraint("project_id", "skill_name", name="uq_project_skill_name"),
    )
    op.create_table(
        "tasks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("beginner", "intermediate", "advanced", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.Column("estimated_hours", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("learning_outcomes", sa.JSON(), nullable=False),
        sa.CheckConstraint("estimated_hours > 0", name="ck_task_hours_positive"),
        sa.CheckConstraint("order_index >= 0", name="ck_task_order_nonnegative"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_id", "order_index", name="uq_task_skill_order"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_task_skill_title", ["skill_id", "title"], unique=False)

    op.create_table(
        "learning_resources",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("roadmap_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "documentation",
                "article",
                "video",
                "course",
                "book",
                "interactive",
                name="resourcetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "difficulty",
            sa.Enum("beginner", "intermediate", "advanced", name="difficulty", native_enum=False),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("relevance_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("recommendation_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "recommended",
                "saved",
                "completed",
                "dismissed",
                name="resourcestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_ai_recommended", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "estimated_minutes IS NULL OR estimated_minutes > 0",
            name="ck_resource_minutes_positive",
        ),
        sa.CheckConstraint(
            "relevance_score IS NULL OR (relevance_score >= 0 AND relevance_score <= 1)",
            name="ck_resource_relevance_range",
        ),
        sa.ForeignKeyConstraint(["roadmap_id"], ["roadmaps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("roadmap_id", "url_hash", name="uq_resource_roadmap_url"),
    )
    with op.batch_alter_table("learning_resources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_resources_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index("ix_resource_roadmap_skill", ["roadmap_id", "skill_id"], unique=False)
        batch_op.create_index("ix_resource_roadmap_task", ["roadmap_id", "task_id"], unique=False)

    op.create_table(
        "subtasks",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=220), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("completion_criteria", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("estimated_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.CheckConstraint("estimated_hours > 0", name="ck_subtask_hours_positive"),
        sa.CheckConstraint("order_index >= 0", name="ck_subtask_order_nonnegative"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "order_index", name="uq_subtask_task_order"),
    )
    with op.batch_alter_table("subtasks", schema=None) as batch_op:
        batch_op.create_index("ix_subtask_task_title", ["task_id", "title"], unique=False)

    op.create_table(
        "progress_records",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learner_id", sa.Uuid(), nullable=False),
        sa.Column("roadmap_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("subtask_id", sa.Uuid(), nullable=True),
        sa.Column(
            "target_type",
            sa.Enum(
                "roadmap", "skill", "task", "subtask", name="progresstargettype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("scope_key", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "not_started",
                "in_progress",
                "completed",
                "blocked",
                name="progressstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("time_spent_minutes", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100", name="ck_progress_percent_range"
        ),
        sa.CheckConstraint("time_spent_minutes >= 0", name="ck_progress_time_nonnegative"),
        sa.ForeignKeyConstraint(["roadmap_id"], ["roadmaps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subtask_id"], ["subtasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "learner_id", "roadmap_id", "scope_key", name="uq_progress_learner_scope"
        ),
    )
    with op.batch_alter_table("progress_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_progress_records_learner_id"), ["learner_id"], unique=False
        )
        batch_op.create_index(
            "ix_progress_roadmap_target", ["roadmap_id", "target_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("progress_records", schema=None) as batch_op:
        batch_op.drop_index("ix_progress_roadmap_target")
        batch_op.drop_index(batch_op.f("ix_progress_records_learner_id"))

    op.drop_table("progress_records")
    with op.batch_alter_table("subtasks", schema=None) as batch_op:
        batch_op.drop_index("ix_subtask_task_title")

    op.drop_table("subtasks")
    with op.batch_alter_table("learning_resources", schema=None) as batch_op:
        batch_op.drop_index("ix_resource_roadmap_task")
        batch_op.drop_index("ix_resource_roadmap_skill")
        batch_op.drop_index(batch_op.f("ix_learning_resources_learner_id"))

    op.drop_table("learning_resources")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_task_skill_title")

    op.drop_table("tasks")
    op.drop_table("project_skills")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_message_conversation_created")

    op.drop_table("messages")
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index("ix_skill_roadmap_title")

    op.drop_table("skills")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_learner_id"))
        batch_op.drop_index("ix_project_roadmap_created")
        batch_op.drop_index("ix_project_learner_fingerprint")
        batch_op.drop_index("ix_project_learner_created")

    op.drop_table("projects")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_learner_id"))
        batch_op.drop_index("ix_conversation_roadmap_recent")
        batch_op.drop_index("ix_conversation_learner_recent")

    op.drop_table("conversations")
    with op.batch_alter_table("roadmaps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roadmaps_learner_id"))
        batch_op.drop_index("ix_roadmap_learner_fingerprint")
        batch_op.drop_index("ix_roadmap_learner_created")
        batch_op.drop_index("ix_roadmap_index_recovery")

    op.drop_table("roadmaps")
    with op.batch_alter_table("response_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_response_cache_learner_id"))
        batch_op.drop_index("ix_response_cache_expires")

    op.drop_table("response_cache")
    with op.batch_alter_table("generation_evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_evaluation_fingerprint")
        batch_op.drop_index("ix_evaluation_entity")

    op.drop_table("generation_evaluations")
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.drop_index("ix_prompt_name_status")

    op.drop_table("prompt_versions")
    op.drop_table("embedding_cache")
    # ### end Alembic commands ###
